### ISSUE TITLE
I have got many problems.

### ISSUE THREAD

**Issue by rfyo7243** [york8817612/Ghost#11]
Unable to find configuration file 'Configuration.ini'.
Server.Common.IO.SettingReadException: Failed to read setting 'Packets'.
There are many errors.
Can you release all the files in your Taiwan Ghost online server emulator? (all server emulator files, bypassed game.exe)
Can you release your Taiwan Ghost online server emulator's all the files? (all server emulator files, bypassed game.exe)
All files..

**Comment by york8817612** [comment]
https://github.com/york8817612/Ghost/releases/download/v1.2/Configuration.ini

**Comment by rfyo7243** [comment]
> https://github.com/york8817612/Ghost/releases/download/v1.2/Configuration.ini

Thank you.
But I have still problems.
Can you read https://github.com/york8817612/Ghost/issues/13 ?
