### ISSUE TITLE
how to enable/disable debug information

### ISSUE THREAD

**Issue by x213212** [york8817612/Ghost#23]
hi i change the project mysql version and comment some code
\Ghost-1.0\Server\GameServer\Ghost\Characters\Character.cs -->Load
```
 //this.Storages.Load();
```
\download\Ghost-1.0\Server\GameServer\Net\Handler\GameHandler.cs -->Game_Log_Req
```
//StoragePacket.getStoreInfo(gc);
//StoragePacket.getStoreMoney(gc);
```
and 
![image](https://user-images.githubusercontent.com/9297254/103471196-40b72e00-4db8-11eb-8372-5ab2089715e4.png)
in 
```
\Ghost-1.0\Server\CharServer\Net\CharHandler.cs
\Ghost-1.0\Server\GameServer\Net\Handler\GameHandler.cs
\Ghost-1.0\Server\LoginServer\Net\LoginHandler.cs
```
add
```
 password = gc.Account.Password;
or
 password = c.Account.Password;

```
InPacket seen not working debuging...
![image](https://user-images.githubusercontent.com/9297254/103471234-bb804900-4db8-11eb-93c4-5b46ec7b04d3.png)
![image](https://user-images.githubusercontent.com/9297254/103471238-c89d3800-4db8-11eb-9e97-5e69adac8865.png)

final working
![image](https://user-images.githubusercontent.com/9297254/103471259-0c903d00-4db9-11eb-9939-875f7ca38bd5.png)

![image](https://user-images.githubusercontent.com/9297254/103471262-13b74b00-4db9-11eb-9994-13c07cebab0e.png)

i have question how to disable/enable debug information
use IDA or OllyDbg tool(? or i miss some step

**Comment by york8817612** [comment]
是的，我使用了IDA和OllDbg
_Yes, I used IDA and OllDbg_
Debug訊息是客戶端的功能
_Debug messages are functions of the client_
需要用IDA去關閉
_Need to use IDA to close_

**Comment by x213212** [comment]
thx ，i used ida enable/disable [work great](https://x8795278.blogspot.com/2021/01/how-to-enabledisable-debug-information.html)

**Comment by armadeas** [comment]
Join Discord Soulsaver Private Server https://discord.gg/VKQvjG7w
