### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by rfyo7243** [york8817612/Ghost#9]
I have a question. 
Can you release Taiwan ghost online 2009 client? Taiwan ghost online old client.

**Comment by york8817612** [comment]
https://github.com/york8817612/Ghost/releases/download/v1.0/Online_.exe

**Comment by rfyo7243** [comment]
> https://github.com/york8817612/Ghost/releases/download/v1.0/Online_.exe

Thank You!
But I have a problem for bypassing game.exe
Can you release the bypassed Game.exe?

**Comment by york8817612** [comment]
https://github.com/york8817612/Ghost/releases/download/v1.1/Game_localhost_Debug.exe

**Comment by rfyo7243** [comment]
> https://github.com/york8817612/Ghost/releases/download/v1.1/Game_localhost_Debug.exe

Thank you so much!

**Comment by rfyo7243** [comment]
> https://github.com/york8817612/Ghost/releases/download/v1.1/Game_localhost_Debug.exe

I run Game_localhost_Debug.exe
But execution error of Game_localhost_Debug.exe
https://github.com/york8817612/Ghost/issues/13 <-(about execution error of Game_localhost)
